name: Atualizar Playlist de Esportes

on:
  schedule:
    # Roda automaticamente todo dia às 06:00 da manhã (UTC)
    - cron: '0 6 * * *'
  workflow_dispatch: # Permite que você execute manualmente quando quiser

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Copiar repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Executar script de filtragem
      run: python update_playlist.py
      
    - name: Salvar alterações no repositório
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add br-sports.m3u
        git diff --quiet && git diff --staged --quiet || (git commit -m "Atualização automática da playlist de esportes" && git push origin main)
